# Generated by Django 4.2.1 on 2024-01-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_markdown_doc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='yaml_content',
            field=models.TextField(blank=True),
        ),
    ]
