# Generated by Django 4.2.1 on 2024-01-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_markdown_doc', '0002_document_yaml_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='yaml_content',
        ),
    ]
